load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "search",
    srcs = ["search.go"],
    importpath = "github.com/cli/cli/v2/pkg/cmd/search",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/cmd/search/code",
        "//pkg/cmd/search/commits",
        "//pkg/cmd/search/issues",
        "//pkg/cmd/search/prs",
        "//pkg/cmd/search/repos",
        "//pkg/cmdutil",
        "@com_github_spf13_cobra//:cobra",
    ],
)
