load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "view",
    srcs = ["view.go"],
    importpath = "github.com/cli/cli/v2/pkg/cmd/run/view",
    visibility = ["//visibility:public"],
    deps = [
        "//api",
        "//internal/browser",
        "//internal/ghinstance",
        "//internal/ghrepo",
        "//internal/text",
        "//pkg/cmd/run/shared",
        "//pkg/cmdutil",
        "//pkg/iostreams",
        "@com_github_makenowjust_heredoc//:heredoc",
        "@com_github_spf13_cobra//:cobra",
    ],
)

go_test(
    name = "view_test",
    srcs = ["view_test.go"],
    embed = [":view"],
    deps = [
        "//internal/browser",
        "//internal/config",
        "//internal/gh",
        "//internal/ghrepo",
        "//internal/prompter",
        "//pkg/cmd/run/shared",
        "//pkg/cmd/workflow/shared",
        "//pkg/cmdutil",
        "//pkg/httpmock",
        "//pkg/iostreams",
        "@com_github_google_shlex//:shlex",
        "@com_github_makenowjust_heredoc//:heredoc",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
    data = glob(["fixtures/**"]),
)
