load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "extension",
    srcs = [
        "command.go",
        "extension.go",
        "git.go",
        "http.go",
        "manager.go",
        "mocks.go",
        "symlink_other.go",
        "symlink_windows.go",
    ],
    embedsrcs = [
        "ext_tmpls/buildScript.sh",
        "ext_tmpls/goBinMain.go.txt",
        "ext_tmpls/goBinWorkflow.yml",
        "ext_tmpls/otherBinWorkflow.yml",
        "ext_tmpls/script.sh",
    ],
    importpath = "github.com/cli/cli/v2/pkg/cmd/extension",
    visibility = ["//visibility:public"],
    deps = [
        "//api",
        "//git",
        "//internal/config",
        "//internal/gh",
        "//internal/ghinstance",
        "//internal/ghrepo",
        "//internal/tableprinter",
        "//internal/text",
        "//pkg/cmd/extension/browse",
        "//pkg/cmdutil",
        "//pkg/extensions",
        "//pkg/findsh",
        "//pkg/iostreams",
        "//pkg/search",
        "@com_github_cli_safeexec//:safeexec",
        "@com_github_makenowjust_heredoc//:heredoc",
        "@com_github_spf13_cobra//:cobra",
        "@com_github_stretchr_testify//mock",
        "@in_gopkg_yaml_v3//:yaml_v3",
    ],
)

go_test(
    name = "extension_test",
    srcs = [
        "command_test.go",
        "extension_test.go",
        "manager_test.go",
    ],
    embed = [":extension"],
    deps = [
        "//git",
        "//internal/browser",
        "//internal/config",
        "//internal/gh",
        "//internal/ghrepo",
        "//internal/prompter",
        "//internal/run",
        "//pkg/cmdutil",
        "//pkg/extensions",
        "//pkg/httpmock",
        "//pkg/iostreams",
        "@com_github_makenowjust_heredoc//:heredoc",
        "@com_github_spf13_cobra//:cobra",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@in_gopkg_yaml_v3//:yaml_v3",
    ],
)
