load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "set",
    srcs = [
        "http.go",
        "set.go",
    ],
    importpath = "github.com/cli/cli/v2/pkg/cmd/secret/set",
    visibility = ["//visibility:public"],
    deps = [
        "//api",
        "//internal/gh",
        "//internal/ghrepo",
        "//pkg/cmd/secret/shared",
        "//pkg/cmdutil",
        "//pkg/iostreams",
        "@com_github_hashicorp_go_multierror//:go-multierror",
        "@com_github_joho_godotenv//:godotenv",
        "@com_github_makenowjust_heredoc//:heredoc",
        "@com_github_spf13_cobra//:cobra",
        "@org_golang_x_crypto//nacl/box",
    ],
)

go_test(
    name = "set_test",
    srcs = ["set_test.go"],
    embed = [":set"],
    deps = [
        "//internal/config",
        "//internal/gh",
        "//internal/ghrepo",
        "//internal/prompter",
        "//pkg/cmd/secret/shared",
        "//pkg/cmdutil",
        "//pkg/httpmock",
        "//pkg/iostreams",
        "@com_github_google_shlex//:shlex",
        "@com_github_makenowjust_heredoc//:heredoc",
        "@com_github_stretchr_testify//assert",
    ],
)
