load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "set",
    srcs = ["set.go"],
    importpath = "github.com/cli/cli/v2/pkg/cmd/alias/set",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/gh",
        "//pkg/cmd/alias/shared",
        "//pkg/cmdutil",
        "//pkg/iostreams",
        "@com_github_makenowjust_heredoc//:heredoc",
        "@com_github_spf13_cobra//:cobra",
    ],
)

go_test(
    name = "set_test",
    srcs = ["set_test.go"],
    embed = [":set"],
    deps = [
        "//internal/config",
        "//internal/gh",
        "//pkg/cmd/alias/shared",
        "//pkg/cmdutil",
        "//pkg/iostreams",
        "@com_github_google_shlex//:shlex",
        "@com_github_spf13_cobra//:cobra",
        "@com_github_stretchr_testify//assert",
    ],
)
