load("@rules_go//go:def.bzl", "go_library")
load("@rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "ssh_proto",
    srcs = ["ssh_server_host_service.v1.proto"],
    visibility = ["//:__subpackages__"],
)

go_proto_library(
    name = "ssh_go_proto",
    compilers = [
        "@rules_go//proto:go_proto",
        "@rules_go//proto:go_grpc_v2",
    ],
    importpath = "github.com/cli/cli/v2/internal/codespaces/rpc/ssh",
    proto = ":ssh_proto",
    visibility = ["//:__subpackages__"],
)

go_library(
    name = "ssh",
    srcs = ["ssh_server_host_service.v1.proto.mock.go"],
    importpath = "github.com/cli/cli/v2/internal/codespaces/rpc/ssh",
    visibility = ["//:__subpackages__"],
    embed = [":ssh_go_proto"],
)
