load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "delete-asset",
    srcs = ["delete_asset.go"],
    importpath = "github.com/cli/cli/v2/pkg/cmd/release/delete-asset",
    visibility = ["//visibility:public"],
    deps = [
        "//api",
        "//internal/ghrepo",
        "//pkg/cmd/release/shared",
        "//pkg/cmdutil",
        "//pkg/iostreams",
        "@com_github_spf13_cobra//:cobra",
    ],
)

go_test(
    name = "delete-asset_test",
    srcs = ["delete_asset_test.go"],
    embed = [":delete-asset"],
    deps = [
        "//internal/ghrepo",
        "//internal/prompter",
        "//pkg/cmd/release/shared",
        "//pkg/cmdutil",
        "//pkg/httpmock",
        "//pkg/iostreams",
        "@com_github_google_shlex//:shlex",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
