load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "secret",
    srcs = ["secret.go"],
    importpath = "github.com/cli/cli/v2/pkg/cmd/secret",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/cmd/secret/delete",
        "//pkg/cmd/secret/list",
        "//pkg/cmd/secret/set",
        "//pkg/cmdutil",
        "@com_github_makenowjust_heredoc//:heredoc",
        "@com_github_spf13_cobra//:cobra",
    ],
)
