load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "delete",
    srcs = [
        "delete.go",
        "http.go",
    ],
    importpath = "github.com/cli/cli/v2/pkg/cmd/repo/deploy-key/delete",
    visibility = ["//visibility:public"],
    deps = [
        "//api",
        "//internal/ghinstance",
        "//internal/ghrepo",
        "//pkg/cmdutil",
        "//pkg/iostreams",
        "@com_github_spf13_cobra//:cobra",
    ],
)

go_test(
    name = "delete_test",
    srcs = ["delete_test.go"],
    embed = [":delete"],
    deps = [
        "//internal/ghrepo",
        "//pkg/httpmock",
        "//pkg/iostreams",
        "@com_github_stretchr_testify//assert",
    ],
)
