load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "shared",
    srcs = ["shared.go"],
    importpath = "github.com/cli/cli/v2/pkg/cmd/secret/shared",
    visibility = ["//visibility:public"],
    deps = ["//internal/text"],
)

go_test(
    name = "shared_test",
    srcs = ["shared_test.go"],
    embed = [":shared"],
    deps = ["@com_github_stretchr_testify//assert"],
)
