load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "list",
    srcs = ["list.go"],
    importpath = "github.com/cli/cli/v2/pkg/cmd/workflow/list",
    visibility = ["//visibility:public"],
    deps = [
        "//api",
        "//internal/ghrepo",
        "//internal/tableprinter",
        "//pkg/cmd/workflow/shared",
        "//pkg/cmdutil",
        "//pkg/iostreams",
        "@com_github_spf13_cobra//:cobra",
    ],
)

go_test(
    name = "list_test",
    srcs = ["list_test.go"],
    embed = [":list"],
    deps = [
        "//internal/ghrepo",
        "//pkg/cmd/workflow/shared",
        "//pkg/cmdutil",
        "//pkg/httpmock",
        "//pkg/iostreams",
        "@com_github_google_shlex//:shlex",
        "@com_github_stretchr_testify//assert",
    ],
)
