load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "markdown",
    srcs = ["markdown.go"],
    importpath = "github.com/cli/cli/v2/pkg/markdown",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_charmbracelet_glamour//:glamour",
        "@com_github_cli_go_gh_v2//pkg/markdown",
    ],
)
