load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "view",
    srcs = [
        "http.go",
        "view.go",
    ],
    importpath = "github.com/cli/cli/v2/pkg/cmd/issue/view",
    visibility = ["//visibility:public"],
    deps = [
        "//api",
        "//internal/browser",
        "//internal/ghrepo",
        "//internal/text",
        "//pkg/cmd/issue/shared",
        "//pkg/cmd/pr/shared",
        "//pkg/cmdutil",
        "//pkg/iostreams",
        "//pkg/markdown",
        "//pkg/set",
        "@com_github_makenowjust_heredoc//:heredoc",
        "@com_github_shurcool_githubv4//:githubv4",
        "@com_github_spf13_cobra//:cobra",
    ],
)

go_test(
    name = "view_test",
    srcs = ["view_test.go"],
    embed = [":view"],
    deps = [
        "//internal/browser",
        "//internal/config",
        "//internal/gh",
        "//internal/ghrepo",
        "//internal/run",
        "//pkg/cmdutil",
        "//pkg/httpmock",
        "//pkg/iostreams",
        "//pkg/jsonfieldstest",
        "//test",
        "@com_github_google_shlex//:shlex",
        "@com_github_stretchr_testify//assert",
    ],
    data = glob(["fixtures/**"]),
)
