load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "login",
    srcs = ["login.go"],
    importpath = "github.com/cli/cli/v2/pkg/cmd/auth/login",
    visibility = ["//visibility:public"],
    deps = [
        "//git",
        "//internal/browser",
        "//internal/gh",
        "//internal/ghinstance",
        "//pkg/cmd/auth/shared",
        "//pkg/cmd/auth/shared/gitcredentials",
        "//pkg/cmdutil",
        "//pkg/iostreams",
        "@com_github_cli_go_gh_v2//pkg/auth",
        "@com_github_makenowjust_heredoc//:heredoc",
        "@com_github_spf13_cobra//:cobra",
    ],
)

go_test(
    name = "login_test",
    srcs = ["login_test.go"],
    embed = [":login"],
    deps = [
        "//git",
        "//internal/config",
        "//internal/gh",
        "//internal/prompter",
        "//internal/run",
        "//pkg/cmdutil",
        "//pkg/httpmock",
        "//pkg/iostreams",
        "@com_github_google_shlex//:shlex",
        "@com_github_makenowjust_heredoc//:heredoc",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
