load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "commits",
    srcs = ["commits.go"],
    importpath = "github.com/cli/cli/v2/pkg/cmd/search/commits",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/browser",
        "//internal/tableprinter",
        "//internal/text",
        "//pkg/cmd/search/shared",
        "//pkg/cmdutil",
        "//pkg/iostreams",
        "//pkg/search",
        "@com_github_makenowjust_heredoc//:heredoc",
        "@com_github_spf13_cobra//:cobra",
    ],
)

go_test(
    name = "commits_test",
    srcs = ["commits_test.go"],
    embed = [":commits"],
    deps = [
        "//internal/browser",
        "//pkg/cmdutil",
        "//pkg/iostreams",
        "//pkg/search",
        "@com_github_google_shlex//:shlex",
        "@com_github_stretchr_testify//assert",
    ],
)
