load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "browse",
    srcs = ["browse.go"],
    importpath = "github.com/cli/cli/v2/pkg/cmd/browse",
    visibility = ["//visibility:public"],
    deps = [
        "//api",
        "//git",
        "//internal/browser",
        "//internal/ghrepo",
        "//internal/text",
        "//pkg/cmdutil",
        "//pkg/iostreams",
        "@com_github_makenowjust_heredoc//:heredoc",
        "@com_github_spf13_cobra//:cobra",
    ],
)

go_test(
    name = "browse_test",
    srcs = ["browse_test.go"],
    embed = [":browse"],
    deps = [
        "//git",
        "//internal/browser",
        "//internal/ghrepo",
        "//pkg/cmdutil",
        "//pkg/httpmock",
        "//pkg/iostreams",
        "@com_github_google_shlex//:shlex",
        "@com_github_stretchr_testify//assert",
    ],
)
