load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "field-list",
    srcs = ["field_list.go"],
    importpath = "github.com/cli/cli/v2/pkg/cmd/project/field-list",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/tableprinter",
        "//pkg/cmd/project/shared/client",
        "//pkg/cmd/project/shared/queries",
        "//pkg/cmdutil",
        "//pkg/iostreams",
        "@com_github_makenowjust_heredoc//:heredoc",
        "@com_github_spf13_cobra//:cobra",
    ],
)

go_test(
    name = "field-list_test",
    srcs = ["field_list_test.go"],
    embed = [":field-list"],
    deps = [
        "//pkg/cmd/project/shared/queries",
        "//pkg/cmdutil",
        "//pkg/iostreams",
        "@com_github_google_shlex//:shlex",
        "@com_github_makenowjust_heredoc//:heredoc",
        "@com_github_stretchr_testify//assert",
        "@in_gopkg_h2non_gock_v1//:gock_v1",
    ],
)
