load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "verify",
    srcs = [
        "attestation.go",
        "options.go",
        "policy.go",
        "verify.go",
    ],
    importpath = "github.com/cli/cli/v2/pkg/cmd/attestation/verify",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/gh",
        "//internal/ghinstance",
        "//internal/text",
        "//pkg/cmd/attestation/api",
        "//pkg/cmd/attestation/artifact",
        "//pkg/cmd/attestation/artifact/oci",
        "//pkg/cmd/attestation/auth",
        "//pkg/cmd/attestation/io",
        "//pkg/cmd/attestation/verification",
        "//pkg/cmdutil",
        "@com_github_cli_go_gh_v2//pkg/auth",
        "@com_github_makenowjust_heredoc//:heredoc",
        "@com_github_sigstore_sigstore_go//pkg/fulcio/certificate",
        "@com_github_sigstore_sigstore_go//pkg/verify",
        "@com_github_spf13_cobra//:cobra",
    ],
)

go_test(
    name = "verify_test",
    srcs = [
        "options_test.go",
        "policy_test.go",
        "verify_test.go",
    ],
    embed = [":verify"],
    deps = [
        "//pkg/cmd/attestation/api",
        "//pkg/cmd/attestation/artifact/oci",
        "//pkg/cmd/attestation/io",
        "//pkg/cmd/attestation/test",
        "//pkg/cmd/attestation/verification",
        "//pkg/cmd/factory",
        "//pkg/cmdutil",
        "//pkg/httpmock",
        "//pkg/iostreams",
        "@com_github_spf13_cobra//:cobra",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
    data = [
        "//pkg/cmd/attestation/test/data:sigstore-js-2.1.0.tgz",
        "//pkg/cmd/attestation/test/data:sigstore-js-2.1.0-bundle.json",
    ],
)
