load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "codespace",
    srcs = [
        "code.go",
        "codespace_selector.go",
        "common.go",
        "create.go",
        "delete.go",
        "edit.go",
        "jupyter.go",
        "list.go",
        "logs.go",
        "mock_api.go",
        "mock_prompter.go",
        "ports.go",
        "rebuild.go",
        "root.go",
        "select.go",
        "ssh.go",
        "stop.go",
        "view.go",
    ],
    importpath = "github.com/cli/cli/v2/pkg/cmd/codespace",
    visibility = ["//visibility:public"],
    deps = [
        "//context",
        "//internal/browser",
        "//internal/codespaces",
        "//internal/codespaces/api",
        "//internal/codespaces/portforwarder",
        "//internal/codespaces/rpc",
        "//internal/ghrepo",
        "//internal/tableprinter",
        "//internal/text",
        "//pkg/cmdutil",
        "//pkg/iostreams",
        "//pkg/ssh",
        "@com_github_alecaivazis_survey_v2//:survey",
        "@com_github_alecaivazis_survey_v2//terminal",
        "@com_github_cli_safeexec//:safeexec",
        "@com_github_makenowjust_heredoc//:heredoc",
        "@com_github_microsoft_dev_tunnels//go/tunnels",
        "@com_github_muhammadmuzzammil1998_jsonc//:jsonc",
        "@com_github_spf13_cobra//:cobra",
        "@org_golang_x_sync//errgroup",
        "@org_golang_x_term//:term",
    ],
)

go_test(
    name = "codespace_test",
    srcs = [
        "code_test.go",
        "codespace_selector_test.go",
        "common_test.go",
        "create_test.go",
        "delete_test.go",
        "edit_test.go",
        "list_test.go",
        "logs_test.go",
        "ports_test.go",
        "rebuild_test.go",
        "select_test.go",
        "ssh_test.go",
        "stop_test.go",
        "view_test.go",
    ],
    embed = [":codespace"],
    deps = [
        "//internal/browser",
        "//internal/codespaces/api",
        "//internal/codespaces/connection",
        "//pkg/cmdutil",
        "//pkg/iostreams",
        "//pkg/ssh",
        "@com_github_alecaivazis_survey_v2//:survey",
        "@com_github_google_shlex//:shlex",
        "@com_github_makenowjust_heredoc//:heredoc",
        "@com_github_stretchr_testify//assert",
    ],
)
