load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "option",
    srcs = ["option.go"],
    importpath = "github.com/cli/cli/v2/pkg/option",
    visibility = ["//visibility:public"],
)

go_test(
    name = "option_test",
    srcs = ["option_test.go"],
    deps = [
        ":option",
        "@com_github_stretchr_testify//require",
    ],
)
