load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "root",
    srcs = [
        "alias.go",
        "extension.go",
        "help.go",
        "help_reference.go",
        "help_topic.go",
        "root.go",
    ],
    importpath = "github.com/cli/cli/v2/pkg/cmd/root",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/run",
        "//internal/text",
        "//pkg/cmd/actions",
        "//pkg/cmd/alias",
        "//pkg/cmd/alias/shared",
        "//pkg/cmd/api",
        "//pkg/cmd/attestation",
        "//pkg/cmd/auth",
        "//pkg/cmd/browse",
        "//pkg/cmd/cache",
        "//pkg/cmd/codespace",
        "//pkg/cmd/completion",
        "//pkg/cmd/config",
        "//pkg/cmd/extension",
        "//pkg/cmd/factory",
        "//pkg/cmd/gist",
        "//pkg/cmd/gpg-key",
        "//pkg/cmd/issue",
        "//pkg/cmd/label",
        "//pkg/cmd/org",
        "//pkg/cmd/pr",
        "//pkg/cmd/project",
        "//pkg/cmd/release",
        "//pkg/cmd/repo",
        "//pkg/cmd/repo/credits",
        "//pkg/cmd/ruleset",
        "//pkg/cmd/run",
        "//pkg/cmd/search",
        "//pkg/cmd/secret",
        "//pkg/cmd/ssh-key",
        "//pkg/cmd/status",
        "//pkg/cmd/variable",
        "//pkg/cmd/version",
        "//pkg/cmd/workflow",
        "//pkg/cmdutil",
        "//pkg/extensions",
        "//pkg/findsh",
        "//pkg/iostreams",
        "//pkg/markdown",
        "@com_github_google_shlex//:shlex",
        "@com_github_makenowjust_heredoc//:heredoc",
        "@com_github_spf13_cobra//:cobra",
        "@com_github_spf13_pflag//:pflag",
    ],
)

go_test(
    name = "root_test",
    srcs = [
        "alias_test.go",
        "extension_test.go",
        "help_test.go",
        "help_topic_test.go",
    ],
    embed = [":root"],
    deps = [
        "//pkg/extensions",
        "//pkg/iostreams",
        "@com_github_makenowjust_heredoc//:heredoc",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
