load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "shared",
    srcs = [
        "display.go",
        "lookup.go",
    ],
    importpath = "github.com/cli/cli/v2/pkg/cmd/issue/shared",
    visibility = ["//visibility:public"],
    deps = [
        "//api",
        "//internal/featuredetection",
        "//internal/ghrepo",
        "//internal/tableprinter",
        "//internal/text",
        "//pkg/cmd/pr/shared",
        "//pkg/iostreams",
        "//pkg/set",
        "@org_golang_x_sync//errgroup",
    ],
)

go_test(
    name = "shared_test",
    srcs = ["lookup_test.go"],
    embed = [":shared"],
    deps = [
        "//internal/ghrepo",
        "//pkg/httpmock",
        "@com_github_stretchr_testify//assert",
    ],
)
