load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "shared",
    srcs = [
        "commentable.go",
        "comments.go",
        "completion.go",
        "display.go",
        "editable.go",
        "editable_http.go",
        "finder.go",
        "params.go",
        "preserve.go",
        "reaction_groups.go",
        "state.go",
        "survey.go",
        "templates.go",
    ],
    importpath = "github.com/cli/cli/v2/pkg/cmd/pr/shared",
    visibility = ["//visibility:public"],
    deps = [
        "//api",
        "//context",
        "//git",
        "//internal/featuredetection",
        "//internal/gh",
        "//internal/ghrepo",
        "//internal/text",
        "//pkg/cmdutil",
        "//pkg/githubtemplate",
        "//pkg/iostreams",
        "//pkg/markdown",
        "//pkg/search",
        "//pkg/set",
        "//pkg/surveyext",
        "@com_github_google_shlex//:shlex",
        "@com_github_shurcool_githubv4//:githubv4",
        "@com_github_spf13_cobra//:cobra",
        "@org_golang_x_sync//errgroup",
    ],
)

go_test(
    name = "shared_test",
    srcs = [
        "display_test.go",
        "finder_test.go",
        "params_test.go",
        "preserve_test.go",
        "survey_test.go",
        "templates_test.go",
    ],
    embed = [":shared"],
    deps = [
        "//api",
        "//context",
        "//git",
        "//internal/featuredetection",
        "//internal/ghrepo",
        "//internal/prompter",
        "//pkg/httpmock",
        "//pkg/iostreams",
        "//test",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
